W8D1/Reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]

  resources :comments, only: [:create]

  resources :subs  

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/subs')
end

W8D1/Reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, presence: true
    validates :subs, presence: true

    has_many :comments, foreign_key: :post_id, dependent: :destroy

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User

     has_many :post_subs,
        foreign_key: :post_id,
        class_name: :PostSub,
        dependent: :destroy,
        inverse_of: :post

    has_many :subs, through: :post_subs, source: :sub

end

W8D1/Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def show
        @post = Post.find(params[:id])
        render :show
    end

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id
        

        if @post.save
            redirect_to post_url(@post)
        else
            flash[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def edit
        @post = current_user.posts.find_by(id: params[:id])
        
        if @post
            render :edit
        else
            flash[:errors] = ["Post not found"]
            redirect_to subs_url
        end
    end
    
    def update
        @post = current_user.posts.find_by(id: params[:id])
        
        if @post && @post.update(post_params)
            redirect_to post_url(@post)
        else
            flash[:errors] = @post.errors.full_messages
            render :edit
        end
    end
    
    def destroy
        @post = current_user.posts.find_by(id: params[:id])

        if @post && @post.destroy
            redirect_to sub_url(@post.sub)
        else
            flash[:errors] = ["Failed Deletion"]
            redirect_to sub_url(@post.sub)
        end
    end
    
    private
    def post_params
        params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end

end

W8D1/Reddit/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/Reddit/app/views/posts/_form.html.erb
<% if post.persisted? %>
    <% action_url = post_url(post) %>
    <h1>Edit Post</h1>
<% else %>
    <% action_url = posts_url %>
    <h1>New Post</h1>
<% end %>

<div>
    <form action="<%= action_url %>" method="POST">

    <% if post.persisted? %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <label>Title:
            <input type="text" name="post[title]" value="<%= post.title %>">
        </label>

        <br>

        <label>Url:
            <input type="text" name="post[url]" value="<%= post.url %>">
        </label>

        <br>

        <label>Content
            <textarea name="post[content]"><%= post.content %></textarea>
        </label>

        <br>

        <label >Choose a sub: </label>
        <input type="hidden" name="post[sub_ids][]" value="">

        <% Sub.all.each do |sub| %>
            <label><%= sub.title %>
            <input
                type="checkbox"
                value="<%= sub.id %>"
                name="post[sub_ids][]"
                <%= "checked" if post.sub_ids.include?(sub.id) %>
            />
            </label>
        <% end %>

        <br>

        <button>Submit</button>

    </form>
</div>

W8D1/Reddit/app/views/posts/edit.html.erb
<%= render "form", post = @post %>

W8D1/Reddit/app/views/posts/new.html.erb
<%= render "form", post: @post %>

W8D1/Reddit/app/views/posts/show.html.erb
<%# Need to display # of upvotes at beginning of h1 title %>
<h1><a href="<%= post_url(@post) %>"><%= @post.title %></a> by <%= @post.author.username %></h1>
<h3>Content</h3>
<p><%= @post.content %></p>

<%# forms for upvote and downvote %>
<button>Upvote</button>
<br>
<button>Downvote</button>
<br>

<%# list all subs %>
<h3>Subs</h3>
<ul>
    <% @post.subs.each do |sub| %>
    <li>
      <a href="<%= sub_url(sub) %>"><%= sub.title %></a> 
    </li>
    <% end %>
</ul>


<h2>Comments</h2>
<a href="<%= new_post_comment_url(@post) %>">Comment on this post!</a>
<br> 

<ul>
    <% @post.comments.each do |comment| %>
    <li>
      <a href="#"><%= comment.body %></a> 
    </li>
    <%# need to add number of upvotes later %>
    <% end %>
</ul>


<%# link to new_comment_url %>
<br>
<br>

<a href="<%= edit_post_url %>">Edit</a>