W8D1/Reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]

  resources :comments, only: [:create]

  resources :subs  

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/subs')
end

W8D1/Reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  description  :text             not null
#
class Sub < ApplicationRecord
    validates :title, :description, presence: true

    belongs_to :moderator,
        foreign_key: :moderator_id,
        class_name: :User

    has_many :post_subs,
        foreign_key: :sub_id,
        class_name: :PostSub,
        dependent: :destroy,
        inverse_of: :sub

    has_many :posts, through: :post_subs, source: :post
end

W8D1/Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_logged_in!, only: [:new, :create, :edit, :update]

    def index
        @subs = Sub.all
        render :index
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id

        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash[:errors] = ["Unable to Create Sub"]
            render :new
        end
    end

    def edit
        @sub = current_user.subs.find_by(id: params[:id])

        if @sub
            render :edit
        else
            flash[:errors] = ["You are not the moderator of this sub, buddy"]
            redirect_to subs_url
        end
    end

    def update
        @sub = current_user.subs.find_by(id: params[:id])

        if @sub && @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description, :moderator_id)
    end

end

W8D1/Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/Reddit/app/views/subs/_links.html.erb
<% if logged_in? %>
    <ul>
      <li>
        <%= current_user.username %>
      </li>
      <li>
        <a href="<%= new_sub_url %>">
          Create a Sub
        </a>
      </li>
      <li>
        <a href="<%= subs_url %>">
          All Subs
        </a>
      </li>
      <li>
        <form action="<%= session_url %>" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <button>
            Log Out
          </button>
        </form> 
      </li>
    </ul>
<% end %>

W8D1/Reddit/app/views/subs/edit.html.erb
<h1>Edit Your Sub</h1>
<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Name
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <textarea name="sub[description]">
      <%= @sub.description %>
    </textarea>
  </label>

  <button>Submit</button>
</form>

W8D1/Reddit/app/views/subs/index.html.erb
<h1>All the Subs</h1>
<ul>
  <% @subs.each do |sub| %>
  <li>
    <a href="<%= sub_url(sub) %>">
      <%= sub.title %>
    </a>
  </li>
  <% end %>
</ul>

W8D1/Reddit/app/views/subs/new.html.erb
<h1>Create a New Sub</h1>
<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Name
    <input type="text" name="sub[title]">
  </label>

  <label>Description
    <textarea name="sub[description]"></textarea>
  </label>

  <button>Submit</button>
</form>

W8D1/Reddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h3>Description</h3>
  <p><%= @sub.description %></p>

  <a href="<%= new_post_url %>">Make a New Post</a>
  <br>

  <ul>
    <% @sub.posts.each do |post| %>
      <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
    <% end %>
  </ul>


<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a> 